# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"

stages:
  - stage: test
    jobs:
      - job: 'validateandtest'
        pool:
          vmimage: windows-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'VS benoit.sautiere(448fc812-f122-47fd-b6dd-08917bda2d30)'
            subscriptionId: '448fc812-f122-47fd-b6dd-08917bda2d30'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'ARMTemploymentTEst'
            location: 'West Europe'
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.SourcesDirectory)/azuredeploy.json'
            csmParametersFile: '$(Build.SourcesDirectory)/parameters.json'
            deploymentMode: 'Validation'
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'VS benoit.sautiere(448fc812-f122-47fd-b6dd-08917bda2d30)'
            ScriptType: 'InlineScript'
            Inline: 'Install-Module Az.Resources -RequiredVersion 1.12 -AllowPrerelease -Force -Scope CurrentUser'
            azurePowerShellVersion: 'LatestVersion'
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'VS benoit.sautiere(448fc812-f122-47fd-b6dd-08917bda2d30)'
            ScriptType: 'InlineScript'
            Inline: |
              $Parameters = @{
                ResourcegroupName     = "ARMTemploymentTEst"
                Templatefile          = ".\azuredeploy.json"
                TemplateParameterfile = ".\parameters.json"
                Mode                  = 'Incremental'
               }
              $Result = Get-AzResourceGroupDeploymentWhatIfResult @Parameters
              $Result
            azurePowerShellVersion: 'LatestVersion'
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'VS benoit.sautiere(448fc812-f122-47fd-b6dd-08917bda2d30)'
            ScriptType: 'FilePath'
            ScriptPath: '$(Build.SourcesDirectory)/checkForDeletion.json'
            ScriptArguments: '-Resourcegroup ARMTemploymentTEst'
            azurePowerShellVersion: 'LatestVersion'